name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t travel-backend .

      # Add deployment steps here if needed (e.g., push to registry, deploy to server)
